#!/bin/sh

# zoxide maybe is to cost to performance
# req trash-cli
# wl-copy for wayland
# xclip for x11

# Basic settings
set autoquit true
set shell sh
set shellopts '-eu'
set ifs "\n"
set scrolloff 10
set sortby name
set ignorecase true
set period 1
set mouse true
set ratios '1:2'

### LF PREVIEWS
# use the one that work on your terminal
# for some rason some terminal dont work with vanila ctpv and stpv config
# like alacritty foot, etc.
# only work on those terminal using the sixel.sh
# kitty work only on ctpv and the kitty protocols sh
# but i like the text preview form ctpv that the pistol...

# Kitty Protocol
# req pistol chroma archiver
# set previewer ~/.config/lf/preview-kitty.sh
# set cleaner ~/.config/lf/cleaner-kitty.sh

# Sixel
# set previewer ~/.config/lf/sixel.sh

# ctpv preview
set previewer ctpv
set cleaner ctpvclear
&ctpv -s $id
&ctpvquit $id

# stpv preview
# set previewer stpv
# set cleaner stpvimgclr
# &stpvimg --listen $id
# cmd on-quit $stpvimg --end $id

# cmd/funcions

cmd open &{{
    for file in $fx; do
        case $(file --mime-type -Lb "$file") in
            text/*)
                lf -remote "send $id \$EDITOR \"$file\""
                ;;
            *)
                ${OPENER:-xdg-open} "$file" >/dev/null 2>&1 &
                ;;
        esac
    done
}}

cmd mkdir ${{
    printf "Directory name(s): "
    read -r ans
    [ -z "$ans" ] && exit 0
    mkdir -p -- $ans && echo "Created: $ans"
}}

cmd delete ${{
    clear
    tput cup $(($(tput lines)/3))
    printf "Delete files:\n"
    printf "%s\n" "$fx"
    printf "\nConfirm deletion? [y/N] "
    read -r ans
    case $ans in
        [Yy]*)
            if command -v trash-put >/dev/null 2>&1; then
                trash-put -- $fx
                lf -remote "send $id echo 'Files moved to trash'"
            else
                printf "trash-cli not found, permanently delete? [y/N] "
                read -r confirm
                case $confirm in
                    [Yy]*)
                        [ -n "$fx" ] && rm -rf -- $fx
                        lf -remote "send $id echo 'Files permanently deleted'"
                        ;;
                    *) lf -remote "send $id echo 'Aborted'";;
                esac
            fi
            ;;
        *) lf -remote "send $id echo 'Aborted'";;
    esac
}}

cmd copy-name ${{
    names=$(basename -a -- $fx)
    if [ -n "${WAYLAND_DISPLAY:-}" ]; then
        printf '%s' "$names" | wl-copy
    elif [ -n "${DISPLAY:-}" ]; then
        printf '%s' "$names" | xclip -selection clipboard
    else
        lf -remote "send $id echoerr 'No clipboard manager found'"
    fi
}}

cmd copy-path ${{
    paths=$(realpath -- $fx)
    if [ -n "${WAYLAND_DISPLAY:-}" ]; then
        printf '%s' "$paths" | wl-copy
    elif [ -n "${DISPLAY:-}" ]; then
        printf '%s' "$paths" | xclip -selection clipboard
    else
        lf -remote "send $id echoerr 'No clipboard manager found'"
    fi
}}

# Opt back into the statfmt/rulerfmt system (required in r41+)
set rulerfmt "%a|%p| \033[7;31m %m \033[0m| \033[7;33m %c \033[0m| \033[7;35m %s \033[0m| \033[7;34m %f \033[0m| %i/%t"

cmd on-select &{{
    if command -v eza >/dev/null 2>&1; then
        info=$(eza -lbdg --time-style long-iso --color=always "$f")
        lf -remote "send $id set statfmt \"$info\""
        if [ -d "$f" ]; then
            info=$(eza -lbdg --total-size --time-style long-iso --color=always "$f")
            lf -remote "send $id set statfmt \"$info\""
        fi
    else
        info=$(ls -ld "$f")
        lf -remote "send $id set statfmt \"$info\""
    fi
    command -v zoxide >/dev/null 2>&1 && zoxide add "$PWD"
}}

# Keybidings
map <enter> shell
map q quit

# Movements
map k up
map j down
map h updir
map l open
map <up> up
map <down> down
map <left> updir
map <right> open

map <c-b> page-up
map <c-f> page-down
map <pgup> page-up
map <pgdn> page-down

map gg top
map G bottom
map <home> top
map <end> bottom

map J bottom
map K top
map <a-j> page-down
map <a-k> page-up

# Misc
map <c-l> redraw
map <c-r> reload
map md mkdir

# Search and Selection
map f find
map / search

map n search-next
map N search-prev

map v invert
map u unselect
map C clear

map <space> :toggle; down
map <c-space> :toggle
map <c-a> :unselect; invert

# File Operations
map DD delete
map p paste
map y copy
map x cut

map E :extract; reload

# Clipboard
map Yn copy-name
map Yp copy-path

# External
map o open
map O $mimeopen --ask $f

# View
map zh set hidden!
map zr set reverse!
map zn set info
map zs set info size
map zt set info time

# Sort
map za :set sortby name; set info size
map sn :set sortby natural; set info
map ss :set sortby size; set info size
map st :set sortby time; set info time
map sa :set sortby atime; set info atime
map sc :set sortby ctime; set info ctime
map se :set sortby ext; set info

# Rename
map r                                    # unmap default
map i rename                             # before extension  ← default lf behavior
map I :rename; cmd-home                  # at very beginning
map A :rename; cmd-end                   # at very end
map a :rename; cmd-right                 # after extension
map c :rename; cmd-end; cmd-delete-home  # new name
map e :rename; cmd-delete-home           # delete name and leave extension

# Unmaping default keybidings
map H
map M
map L
map m

# Shortcuts
map gd cd ~/Documents
map gD cd ~/Downloads
map gp cd ~/Pictures
map gc cd ~/.config
map gM cd /mnt
map gs cd ~/.local/bin
map gh cd ~
map gT cd ~/.local/share/Trash/files
