#!/bin/sh

#
# ~/.config/shell/aliasrc
#

# Based on luke smith

### Alias

# Verbosity and settings that you pretty much just always are going to want
alias \
	cp="cp -iv"	\
	..="z .."	\
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	ls="lsd --group-dirs first"	\
	lsa="lsd -A --group-dirs first"	\
	lss="lsd -lAh --group-dirs first"	\
	ll="lsd -lA --group-dirs first --total-size"	\
	lls="lsd -lAS --group-dirs first --total-size"	\
	zs='eza --group-directories-first --icons'	\
	zsa='eza -a --group-directories-first --icons'	\
	zss='eza -labg --group-directories-first --time-style long-iso --icons'	\
	zl='eza -labg --group-directories-first --total-size --time-style long-iso --icons'	\
	zls='eza -glabrs size --group-directories-first --total-size --time-style long-iso --icons'	\
	rsync="rsync -vrPlu" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ytt="yt --skip-download --write-thumbnail" \
	ffmpeg="ffmpeg -hide_banner"	\
	z="zoxide"	\
	tfan-auto="echo level auto | sudo tee /proc/acpi/ibm/fan"	\
	tfan-7="echo level 7 | sudo tee /proc/acpi/ibm/fan" 	\
	tfan-full="echo level disengaged | sudo tee /proc/acpi/ibm/fan"	\
	hx="helix"	\



# These common commands are just too long! Abbreviate them
alias \
	ns="nsxiv-rifle"	\
	powersave="sudo cpupower frequency-set -g powersave"	\
	performance="sudo cpupower frequency-set -g performance"	\


# Colorize commands when possible
alias \
	grep="grep --color=auto"	\
	diff="diff --color=auto"	\
	ccat="highlight --out-format=ansi"	\
	ip="ip -color=auto"	\
