#!/bin/sh

# XDG Base Directory spec
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"

# if [ -z "$DBUS_SESSION_BUS_ADDRESS" ] && [ -n "$XDG_RUNTIME_DIR" ]; then
#   export DBUS_SESSION_BUS_ADDRESS="unix:path=$XDG_RUNTIME_DIR/bus"
# fi

# Add ~/.local/bin and ~/.local/bin/* if they exist
[ -d "$HOME/.local/bin" ] && PATH="$PATH:$HOME/.local/bin"

for d in "$HOME/.local/bin"/*; do
  [ -d "$d" ] && PATH="$PATH:$d"
done

[ -d "$HOME/.config/emacs/bin" ] && PATH="$PATH:$HOME/.config/emacs/bin"

# Default programs (some need wrapper scripts)
export EDITOR="nvim"
export EMACS="emacs-launch"
export EMACS_DEBUG="emacs-debug"
export TERMINAL="kitty"
export TERMINAL_PROG="kitty"
export BROWSER="firefox"
export FILEMANAGER="pcmanfm"
export LOCKER_X11="slock"
export LOCKER_WAYLAND="swaylock-launch"
export LAUNCHER_X11="dmenu-launch"
export LAUNCHER_WAYLAND="wmenu-run"

# Firefox
if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
  export MOZ_ENABLE_WAYLAND=1
fi

export MOZ_GTK_TITLEBAR_DECORATION=system
export GTK_CSD=0

# Man Pager
# Bat error with mandoc
# https://github.com/sharkdp/bat/issues/1145
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANROFFOPT="-c"

# Nvim
# export MANPAGER="nvim -c 'set ft=man' -"

# SSH
# Enable only if using ssh-agent
# export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

# XDG user dirs
export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export XDG_DOCUMENTS_DIR="$HOME/Documents"
export XDG_PICTURES_DIR="$HOME/Pictures"

# Shared shell history file (XDG state)
export HISTFILE="${HISTFILE:-$XDG_STATE_HOME/shell_history}"

[ -f "$HISTFILE" ] || {
  mkdir -p "$(dirname "$HISTFILE")"
  : > "$HISTFILE"
  chmod 600 "$HISTFILE"
}

# Using XDG for software that supported
export NO_AT_BRIDGE=1
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export EMACSINIT="$HOME/.config/emacs/init.el"
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
export KODI_DATA="$XDG_DATA_HOME/kodi"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export ANDROID_SDK_HOME="$XDG_CONFIG_HOME/android"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GOPATH="$XDG_DATA_HOME/go"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
export ANSIBLE_CONFIG="$XDG_CONFIG_HOME/ansible/ansible.cfg"
export UNISON="$XDG_DATA_HOME/unison"
export MBSYNCRC="$XDG_CONFIG_HOME/mbsync/config"
export ELECTRUMDIR="$XDG_DATA_HOME/electrum"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"
export RENPY_PATH_TO_SAVES="$XDG_DATA_HOME"
export NPM_CONFIG_INIT_MODULE="$XDG_CONFIG_HOME/npm/config/npm-init.js"
export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm"
export NPM_CONFIG_TMP="$XDG_RUNTIME_DIR/npm"

export QT_QPA_PLATFORMTHEME=qt5ct
export QT6_QPA_PLATFORMTHEME=qt6ct

export XCURSOR_PATH="$XDG_DATA_HOME/icons:$HOME/.icons:/usr/share/icons:/usr/local/share/icons"
