#!/usr/bin/env sh

run() {
    command -v "$1" >/dev/null 2>&1 || return 0
    pgrep -x "$1" >/dev/null 2>&1 || "$@" &
}

run_no_check() {
    command -v "$1" >/dev/null 2>&1 || return 0
    "$@" &
}

run nitrogen --restore
run emacs --daemon
run udiskie
run lxqt-policykit-agent
run picom --config "$HOME/.config/picom/picom.conf"

command -v wmname >/dev/null 2>&1 && wmname LG3D
