#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &

$HOME/.config/polybar/init.sh

nitrogen --restore

wmname LG3D

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config single_monocle       true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


bspc rule -a gammy state=floating
# bspc rule -a mpv state=floating
bspc rule -a mediainfo-gui state=floating
bspc rule -a galculator state=floating
bspc rule -a Emacs state=tiled


udiskie &
lxpolkit &
lxsession &
#gammy &
