#!/usr/bin/env sh

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &
pgrep -x nitrogen > /dev/null || nitrogen --restore &

xrandr --output eDP1 --primary --mode 1920x1080 --pos 1920x0 --rotate normal --output DP1 --off --output DP2 --off --output DP3 --off --output DP4 --off --output HDMI1 --mode 1920x1080 --pos 0x0 --rotate normal --output VIRTUAL1 --off

wmname LG3D

for monitor in $(bspc query -M --names); do
    bspc monitor $monitor -d 1 2 3 4 5 6 7 8 9 10
done

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config single_monocle       true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a gammy state=floating
# bspc rule -a mpv state=floating
bspc rule -a mediainfo-gui state=floating
bspc rule -a galculator state=floating
bspc rule -a Emacs state=tiled

pgrep -x udiskie > /dev/null || udiskie &
pgrep -x lxqt-policykit > /dev/null || lxqt-policykit &

$HOME/.config/polybar/init.sh
# to change bar size need to be change in 2 files
# ~/.config/polybar/config.ini in [bar/bar1] and [bar/bar2]
# ~/.config/bspwm/polybar_toggle.sh
# maybe here using bspc config -m $monitor top_padding 18
# idk
# TODO use a varieble to avoid duplication of code
