#!/usr/bin/env bash

### BASIC

# TERMINAL
super + Return
  $TERMINAL

# CLOSE AND KILL
super + {_,shift + }q
  bspc node -{c,k}

# LAUNCHER
super + d
  $LAUNCHER_X11

# LOCK AND SUSPEND
super + alt + x
  $LOCKER_X11

super + ctrl + x
  $LOCKER_X11 & systemctl suspend

# QUIT / RESTART bspwm
super + alt + {q,r}
  bspc {quit,wm -r}

# RELOAD CONFIGS
super + {Escape,shift + p}
  pkill -USR1 -x {sxhkd,polybar}

# TOGGLE POLYBAR VISIBILITY
super + b
  ~/.config/bspwm/polybar_toggle.sh

### SCRATCHPADS TODO


### WIN MOVEMENTS

# FOCUS, SEND TO DESKTOP
super + {_,shift + }{1-9,0}
  bspc {desktop -f,node -d} '{1-9,10}.local'

# FOCUS / MOVE WINDOW IN CURRENT DESKTOP
super + {_,shift + }{h,j,k,l}
  bspc node -{f,s} {west,south,north,east}

# CYCLE WINDOWS IN CURRENT DESKTOP
super + {_,shift + }c
  bspc node -f {next,prev}.local.!hidden.window

# FOCUS ADJACENT DESKTOP
super + bracket{left,right}
  bspc desktop -f {prev,next}.local

super + {g,semicolon}
  bspc desktop -f {prev,next}.local

alt + {j,k}
  bspc desktop -f {prev,next}.local

# SEND TO ADJACENT DESKTOP
super + shift + bracket{left,right}
  bspc node -d {prev,next}.local

super + shift + {g,semicolon}
  bspc node -d {prev,next}.local

alt + shift + {j,k}
  bspc node -d {prev,next}.local

# FOCUS LAST DESKTOP IN CURRENT MONITOR
super + Tab
  bspc desktop -f last.local

# CHANGE SIZE OF WINDOW TODO
# super + alt + {h,j,k,l}
#   bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# super + alt + shift + {h,j,k,l}
#   bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

super + alt + {Left,Down,Up,Right}
  bspc node -z {left -20 0 || bspc node -z right -20 0, \
                bottom 0 20 || bspc node -z top 0 20, \
                top 0 -20 || bspc node -z bottom 0 -20, \
                right 20 0 || bspc node -z left 20 0}

super + alt + shift + {Left,Down,Up,Right}
  bspc node -z {right -20 0, top 0 20, bottom 0 -20, left 20 0}

### MULTI-MONITORS

# CYCLE MONITOR
super + {comma,period}
  bspc monitor -f {next,prev}

# SEND WINDOW TO ADJACENT MONITOR
super + shift + {comma,period}
  bspc node -m {next,prev} --follow

# FOCUS LAST MONITOR FOCUSED
super + ctrl + Tab
  bspc monitor -f last

# FOCUS N MONITOR
# super + alt + {1-9,0}
#   bspc monitor -f '^{1-9,10}'

# SEND WINDOW TO N MONITOR
# super + alt + shift + {1-9,0}
#   bspc node -m '^{1-9,10}'

### FLOATING WINDOWS

# MOVE FLOATING WINDOW
super + {Left,Down,Up,Right}
  bspc node -v {-20 0,0 20,0 -20,20 0}

### LAYOUT

# MONOCLE
super + m
  bspc desktop -l next

# TILED, FLOATING, FULLSCREEN
super + {t,shift + space,f}
  bspc node -t {tiled,floating,\~fullscreen}

# STICKY
super + alt + s
  bspc node -g sticky

### PRESELECTION

# PRESELECT DIRECTION
super + ctrl + {h,j,k,l}
  bspc node -p {west,south,north,east}

# PRESELECT RATIO
super + ctrl + {1-9}
  bspc node -o 0.{1-9}

# CANCEL PRESELECTION
super + ctrl + {_,shift + }space
  {bspc node -p cancel, bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel}

### LAUNCHERS
super + {w,e,y}
  {$BROWSER,$FILEMANAGER,gammy}

super + {_,shift + }a
  {$EMACS,$EMACS_DEBUG}

### MEDIA KEYS
XF86AudioLowerVolume
  wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-

XF86AudioRaiseVolume
  wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+

XF86AudioMute
  wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

XF86AudioMicMute
  pactl set-source-mute @DEFAULT_SOURCE@ toggle

XF86MonBrightnessUp
  brightnessctl s +2%

XF86MonBrightnessDown
  brightnessctl s 2%-

Print
  flameshot gui
